# Generated by Django 5.2.7 on 2025-10-14 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_wishlist_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistitems',
            name='wishlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.wishlist'),
        ),
    ]
