# Generated by Django 5.2.7 on 2025-10-15 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_cart_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='proceed_to_order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.proceedtoorder'),
        ),
    ]
